import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import LayoutClient from "./layoutclient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <LayoutClient>   {children}</LayoutClient>
        </body>
    </html>
  );
}
